apiVersion: batch/v1
kind: Job
metadata:
  name: readpandas
spec:
   backoffLimit: 3
   activeDeadLineSeconds: 60
   template: 
    spec:
      containers:
      - name: readshow
        image: jonasdocker83/jonas_mod4_desafio:latest
        env:
          - name: MINHA_VAR
            valueFrom: 
              configMapKeyRef:
                name: ambiente
                key: minha_var
        command: ["python", "-c","import os; print(os.environ['MINHA_VAR'])"]
      restartPolicy: Never